# -*- coding: utf-8 -*-
"""GP-Face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyuC8xTgXxIkI7ee332cMCzf9qsOptnC

## import libraries
"""

import cv2
import numpy as np
import base64
import os
import time

from IPython.display import display, Javascript
from google.colab.output import eval_js

"""## camera capture function"""

def start_camera_stream():
  js = Javascript('''
    async function streamFrames() {

      const div = document.createElement('div');
      const video = document.createElement('video');
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');

      const stream = await navigator.mediaDevices.getUserMedia({video: true});
      document.body.appendChild(div);
      div.appendChild(video);

      video.srcObject = stream;
      await video.play();

      canvas.width = 640;
      canvas.height = 480;
      div.appendChild(canvas);

      window.stopCapture = false;

      function drawOverlay() {
        ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

        //  Instruction text
        ctx.fillStyle = "white";
        ctx.font = "24px Arial";
        ctx.textAlign = "center";
        ctx.fillText("Put your face in the frame", canvas.width/2, 40);

        //  Dark overlay
        ctx.fillStyle = "rgba(0,0,0,0.5)";
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        //  Clear oval (face guide)
        ctx.globalCompositeOperation = 'destination-out';
        ctx.beginPath();
        ctx.ellipse(canvas.width/2, canvas.height/2, 120, 160, 0, 0, Math.PI * 2);
        ctx.fill();

        ctx.globalCompositeOperation = 'source-over';

        //  Oval border
        ctx.strokeStyle = "white";
        ctx.lineWidth = 3;
        ctx.beginPath();
        ctx.ellipse(canvas.width/2, canvas.height/2, 120, 160, 0, 0, Math.PI * 2);
        ctx.stroke();

        if (!window.stopCapture) {
          requestAnimationFrame(drawOverlay);
        }
      }

      drawOverlay();

      async function captureFrame() {
        if (window.stopCapture) return null;

        ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
        return canvas.toDataURL('image/jpeg');
      }

      window.captureFrame = captureFrame;

      window.stopStream = () => {
        window.stopCapture = true;
        stream.getTracks().forEach(track => track.stop());
        div.remove();

      };
      window.cameraReady = true;
    }

    streamFrames();
  ''')
  display(js)

"""## load face"""

# Create folder for saving faces
os.makedirs("faces", exist_ok=True)


face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

# Start camera
start_camera_stream()

print("start camera!")

#  Wait for JS
while True:
    ready = eval_js("window.cameraReady === true")
    if ready:
        break

print("Camera started!")

while True:
    data = eval_js("captureFrame()")
    if data is None:
        break


    binary = base64.b64decode(data.split(',')[1])
    img_array = np.frombuffer(binary, np.uint8)
    img = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    h, w = img.shape[:2]
    center_x, center_y = w // 2, h // 2

    for (x, y, fw, fh) in faces:
        face_cx = x + fw // 2
        face_cy = y + fh // 2


        if abs(face_cx - center_x) < 120 and abs(face_cy - center_y) < 160:

            face_crop = img[y:y+fh, x:x+fw]

            filename = f"faces/face_{int(time.time())}.jpg"
            cv2.imwrite(filename, face_crop)

            print(f"Face aligned → Saved at {filename}")


            eval_js("stopStream()")
            break
    else:
        continue
    break